version: '3.4'
  
networks:
  web:
    external:
      name: web
services:
  ui:
    labels:
      - 'traefik.backend=go-ui'
      - 'traefik.port=8045'
      - 'traefik.frontend.rule=Host:gothereforeministries.org'
    networks:
      web:
    image: wayimp/go-ui
    ports:
      - 8045:8045